export const FEATURE_KEYS = {
  ADMIN: 'ADMIN',
  ADMIN_USERS: 'ADMIN_USERS',
  ADMIN_ROLES: 'ADMIN_ROLES',
  ADMIN_ORG_TREE: 'ADMIN_ORG_TREE',
  ADMIN_STORES: 'ADMIN_STORES',
  ADMIN_REGIONS: 'ADMIN_REGIONS',
  ADMIN_PERSONNEL: 'ADMIN_PERSONNEL',
  ADMIN_FEATURES: 'ADMIN_FEATURES',
  ADMIN_POLICIES: 'ADMIN_POLICIES',
  ADMIN_FEEDBACK: 'ADMIN_FEEDBACK',
  ADMIN_SALES_REPORTS: 'ADMIN_SALES_REPORTS',
  ADMIN_SALES_TARGETS: 'ADMIN_SALES_TARGETS',
  ADMIN_QUICK_ACTION_CODES: 'ADMIN_QUICK_ACTION_CODES',
  HOME_DASHBOARD: 'HOME_DASHBOARD',
  HOME_DASHBOARD_SALES: 'HOME_DASHBOARD_SALES',
  HOME_DASHBOARD_FINANCE: 'HOME_DASHBOARD_FINANCE',
  FIFO: 'FIFO',
  FIFO_IMPORT: 'FIFO_IMPORT',
  WARRANTY: 'WARRANTY',
  VIETQR: 'VIETQR',
  BANK_STATEMENTS: 'BANK_STATEMENTS',
  OFFSET_ADJUSTMENTS: 'OFFSET_ADJUSTMENTS',
  PAYMENT_MONITOR: 'PAYMENT_MONITOR',
  PAYMENT_SPEAKER: 'PAYMENT_SPEAKER',
  FEEDBACK: 'FEEDBACK',
  SALES_REPORT: 'SALES_REPORT',
  QUICK_ACTIONS: 'QUICK_ACTIONS',
  QUICK_ACTION_FIFO: 'QUICK_ACTION_FIFO',
  QUICK_ACTION_VIETQR: 'QUICK_ACTION_VIETQR',
  QUICK_ACTION_FOLLOW_UP: 'QUICK_ACTION_FOLLOW_UP',
  QUICK_ACTION_SALES_REPORT: 'QUICK_ACTION_SALES_REPORT',
  QUICK_ACTION_APP_DOWNLOAD: 'QUICK_ACTION_APP_DOWNLOAD',
  QUICK_ACTION_CHECK_IN: 'QUICK_ACTION_CHECK_IN',
  QUICK_ACTION_ZALO_OA: 'QUICK_ACTION_ZALO_OA',
  QUICK_ACTION_GOOGLE_MAP: 'QUICK_ACTION_GOOGLE_MAP',
} as const;

export const DEFAULT_FEATURE_DEFINITIONS = [
  {
    code: FEATURE_KEYS.ADMIN,
    displayName: 'Quản trị',
    description: 'Menu quản trị chung',
    sortOrder: 10,
  },
  {
    code: FEATURE_KEYS.ADMIN_USERS,
    displayName: 'Quản lý người dùng',
    description: 'Tạo và sửa tài khoản nhân sự',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 20,
  },
  {
    code: FEATURE_KEYS.ADMIN_ROLES,
    displayName: 'Quản lý vai trò',
    description: 'Quản lý quyền hệ thống',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 30,
  },
  {
    code: FEATURE_KEYS.ADMIN_ORG_TREE,
    displayName: 'Cơ cấu tổ chức',
    description: 'Quản lý cây tổ chức Lv0-Lv5',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 40,
  },
  {
    code: FEATURE_KEYS.ADMIN_STORES,
    displayName: 'Legacy SR',
    description: 'Legacy: đã thay bằng Cơ cấu tổ chức',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 900,
    visibleInUserPicker: false,
  },
  {
    code: FEATURE_KEYS.ADMIN_REGIONS,
    displayName: 'Legacy Vùng/Miền',
    description: 'Legacy: đã thay bằng Cơ cấu tổ chức',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 901,
    visibleInUserPicker: false,
  },
  {
    code: FEATURE_KEYS.ADMIN_PERSONNEL,
    displayName: 'Danh mục nhân sự',
    description: 'Quản lý phòng ban và chức danh',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 75,
  },
  {
    code: FEATURE_KEYS.ADMIN_FEATURES,
    displayName: 'Quản lý tính năng',
    description: 'Bật/tắt tính năng theo rule',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 70,
  },
  {
    code: FEATURE_KEYS.ADMIN_POLICIES,
    displayName: 'Quản lý policy',
    description: 'Quản lý rule quyền và cấu hình hệ thống',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 80,
  },
  {
    code: FEATURE_KEYS.ADMIN_FEEDBACK,
    displayName: 'Danh sách góp ý',
    description: 'Xem danh sách góp ý nội bộ',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 90,
    visibleInUserPicker: false,
  },
  {
    code: FEATURE_KEYS.ADMIN_SALES_REPORTS,
    displayName: 'Báo cáo bán hàng',
    description: 'Xem, lọc và xuất báo cáo bán hàng',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 95,
  },
  {
    code: FEATURE_KEYS.ADMIN_SALES_TARGETS,
    displayName: 'Quản lý doanh số',
    description: 'Cập nhật chỉ tiêu doanh số theo tháng và phạm vi showroom',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 96,
  },
  {
    code: FEATURE_KEYS.ADMIN_QUICK_ACTION_CODES,
    displayName: 'Quản lý mã thao tác nhanh',
    description: 'Cấu hình liên kết QR theo showroom',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 97,
  },
  {
    code: FEATURE_KEYS.HOME_DASHBOARD,
    displayName: 'Dashboard',
    description: 'Nhóm quyền xem các khu vực trên Trang chủ',
    sortOrder: 97,
  },
  {
    code: FEATURE_KEYS.HOME_DASHBOARD_SALES,
    displayName: 'Dashboard - Bán hàng',
    description: 'Xem khu vực Bán hàng trên Trang chủ',
    parentCode: FEATURE_KEYS.HOME_DASHBOARD,
    sortOrder: 98,
  },
  {
    code: FEATURE_KEYS.HOME_DASHBOARD_FINANCE,
    displayName: 'Dashboard - Tài chính',
    description: 'Xem khu vực Tài chính trên Trang chủ',
    parentCode: FEATURE_KEYS.HOME_DASHBOARD,
    sortOrder: 99,
  },
  {
    code: FEATURE_KEYS.FIFO,
    displayName: 'FIFO',
    description: 'Kiểm tra và sắp xếp FIFO',
    sortOrder: 100,
  },
  {
    code: FEATURE_KEYS.FIFO_IMPORT,
    displayName: 'Import tồn kho',
    description: 'Import tồn kho FIFO thủ công',
    parentCode: FEATURE_KEYS.FIFO,
    sortOrder: 110,
  },
  {
    code: FEATURE_KEYS.WARRANTY,
    displayName: 'BH / SC',
    description: 'Bảo hành và sửa chữa',
    sortOrder: 200,
  },
  {
    code: FEATURE_KEYS.VIETQR,
    displayName: 'VietQR',
    description: 'Tạo QR chuyển khoản',
    sortOrder: 300,
  },
  {
    code: FEATURE_KEYS.BANK_STATEMENTS,
    displayName: 'Sao kê',
    description: 'Rà soát sao kê MAP/VietinBank',
    sortOrder: 400,
  },
  {
    code: FEATURE_KEYS.OFFSET_ADJUSTMENTS,
    displayName: 'Cấn trừ',
    description: 'Tạo và xác nhận hồ sơ cấn trừ',
    sortOrder: 450,
  },
  {
    code: FEATURE_KEYS.PAYMENT_MONITOR,
    displayName: 'Tiền vào',
    description: 'Theo dõi giao dịch tiền vào',
    sortOrder: 500,
  },
  {
    code: FEATURE_KEYS.PAYMENT_SPEAKER,
    displayName: 'Đọc loa',
    description: 'Đọc loa thông báo tiền vào trên thiết bị hỗ trợ',
    parentCode: FEATURE_KEYS.PAYMENT_MONITOR,
    sortOrder: 510,
  },
  {
    code: FEATURE_KEYS.FEEDBACK,
    displayName: 'Góp ý',
    description: 'Gửi góp ý nội bộ',
    sortOrder: 600,
  },
  {
    code: FEATURE_KEYS.SALES_REPORT,
    displayName: 'Báo cáo',
    description: 'Gửi báo cáo bán hàng mua hàng và chưa mua hàng',
    sortOrder: 620,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTIONS,
    displayName: 'Thao tác nhanh',
    description: 'Nhóm thao tác nhanh trên thanh điều hướng và Trang chủ',
    sortOrder: 700,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_FIFO,
    displayName: 'Thao tác nhanh - Kiểm tra FIFO',
    description: 'Hiện lối tắt Kiểm tra FIFO',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 710,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_VIETQR,
    displayName: 'Thao tác nhanh - VietQR',
    description: 'Hiện lối tắt VietQR',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 720,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_FOLLOW_UP,
    displayName: 'Thao tác nhanh - Chăm sóc lại',
    description: 'Hiện lối tắt Chăm sóc lại',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 725,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_SALES_REPORT,
    displayName: 'Thao tác nhanh - Báo cáo bán hàng',
    description: 'Hiện lối tắt Báo cáo bán hàng',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 730,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_APP_DOWNLOAD,
    displayName: 'Thao tác nhanh - Tải app',
    description: 'Hiện mã QR tải ứng dụng của showroom',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 740,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_CHECK_IN,
    displayName: 'Thao tác nhanh - Check-in',
    description: 'Hiện mã QR check-in của showroom',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 750,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_ZALO_OA,
    displayName: 'Thao tác nhanh - Zalo OA',
    description: 'Hiện mã QR Zalo OA của showroom',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 760,
  },
  {
    code: FEATURE_KEYS.QUICK_ACTION_GOOGLE_MAP,
    displayName: 'Thao tác nhanh - GG Map',
    description: 'Hiện mã QR Google Map của showroom',
    parentCode: FEATURE_KEYS.QUICK_ACTIONS,
    sortOrder: 770,
  },
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[keyof typeof FEATURE_KEYS];
