export const FEATURE_KEYS = {
  ADMIN: 'ADMIN',
  ADMIN_USERS: 'ADMIN_USERS',
  ADMIN_ROLES: 'ADMIN_ROLES',
  ADMIN_STORES: 'ADMIN_STORES',
  ADMIN_REGIONS: 'ADMIN_REGIONS',
  ADMIN_PERSONNEL: 'ADMIN_PERSONNEL',
  ADMIN_FEATURES: 'ADMIN_FEATURES',
  ADMIN_POLICIES: 'ADMIN_POLICIES',
  ADMIN_FEEDBACK: 'ADMIN_FEEDBACK',
  FIFO: 'FIFO',
  FIFO_IMPORT: 'FIFO_IMPORT',
  WARRANTY: 'WARRANTY',
  VIETQR: 'VIETQR',
  BANK_STATEMENTS: 'BANK_STATEMENTS',
  PAYMENT_MONITOR: 'PAYMENT_MONITOR',
  FEEDBACK: 'FEEDBACK',
} as const;

export const DEFAULT_FEATURE_DEFINITIONS = [
  {
    code: FEATURE_KEYS.ADMIN,
    displayName: 'Quản trị',
    description: 'Menu quản trị chung',
    sortOrder: 10,
  },
  {
    code: FEATURE_KEYS.ADMIN_USERS,
    displayName: 'Quản lý người dùng',
    description: 'Tạo và sửa tài khoản nhân sự',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 20,
  },
  {
    code: FEATURE_KEYS.ADMIN_ROLES,
    displayName: 'Quản lý vai trò',
    description: 'Quản lý quyền hệ thống',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 30,
  },
  {
    code: FEATURE_KEYS.ADMIN_STORES,
    displayName: 'Quản lý SR',
    description: 'Quản lý showroom/SR và tài khoản liên quan',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 40,
  },
  {
    code: FEATURE_KEYS.ADMIN_REGIONS,
    displayName: 'Quản lý Vùng/Miền',
    description: 'Quản lý Miền, Vùng và scope ảo',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 50,
  },
  {
    code: FEATURE_KEYS.ADMIN_PERSONNEL,
    displayName: 'Quản lý phòng ban/chức danh',
    description: 'Quản lý catalog nhân sự',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 60,
  },
  {
    code: FEATURE_KEYS.ADMIN_FEATURES,
    displayName: 'Quản lý tính năng',
    description: 'Bật/tắt tính năng theo rule',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 70,
  },
  {
    code: FEATURE_KEYS.ADMIN_POLICIES,
    displayName: 'Quản lý policy',
    description: 'Quản lý rule quyền và cấu hình hệ thống',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 80,
  },
  {
    code: FEATURE_KEYS.ADMIN_FEEDBACK,
    displayName: 'Danh sách phản hồi',
    description: 'Xem danh sách phản hồi nội bộ',
    parentCode: FEATURE_KEYS.ADMIN,
    sortOrder: 90,
    visibleInUserPicker: false,
  },
  {
    code: FEATURE_KEYS.FIFO,
    displayName: 'FIFO',
    description: 'Kiểm tra và sắp xếp FIFO',
    sortOrder: 100,
  },
  {
    code: FEATURE_KEYS.FIFO_IMPORT,
    displayName: 'Import tồn kho',
    description: 'Import tồn kho FIFO thủ công',
    parentCode: FEATURE_KEYS.FIFO,
    sortOrder: 110,
  },
  {
    code: FEATURE_KEYS.WARRANTY,
    displayName: 'BH / SC',
    description: 'Bảo hành và sửa chữa',
    sortOrder: 200,
  },
  {
    code: FEATURE_KEYS.VIETQR,
    displayName: 'VietQR',
    description: 'Tạo QR chuyển khoản',
    sortOrder: 300,
  },
  {
    code: FEATURE_KEYS.BANK_STATEMENTS,
    displayName: 'Sao kê',
    description: 'Rà soát sao kê MAP/VietinBank',
    sortOrder: 400,
  },
  {
    code: FEATURE_KEYS.PAYMENT_MONITOR,
    displayName: 'Tiền vào',
    description: 'Theo dõi giao dịch tiền vào',
    sortOrder: 500,
  },
  {
    code: FEATURE_KEYS.FEEDBACK,
    displayName: 'Phản hồi',
    description: 'Gửi phản hồi nội bộ',
    sortOrder: 600,
  },
] as const;

export type FeatureKey = (typeof FEATURE_KEYS)[keyof typeof FEATURE_KEYS];
